apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: your-aws-account-id.dkr.ecr.ap-south-1.amazonaws.com/your-repo-name:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
      volumes:
      - name: static-volume
        emptyDir: {}
